trigger:
  - master

pool:
  name: Default

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'package'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '21.0.3'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      failTaskOnFailedTests: false
