trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'
    jdkArchitectureOption: 'x64'
    goals: 'package -Dmaven.test.failure.ignore=true'
  continueOnError: true

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    failTaskOnFailedTests: false
  continueOnError: true
